assets/urls.py
from django.conf.urls import url
from assets import views

app_name = 'assets'


urlpatterns = [
    url(r'^asset/$', views.AssetListView, name='asset-list'),
    url(r'^asset/detail/$', views.AssetDetailView, name='asset_detail'),
    url(r'^asset/delete/$', views.AssetDeleteView, name='asset_delete'),
    url(r'^asset/create/$', views.AssetCreateView, name='asset_create'),

]

c13/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from c13 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexViews),
    url(r'^personal/', views.personal, name='personal'),
    url(r'^accounts/logout/',views.logout,name='logout'),
    url(r'^accounts/login/',views.login,name='login'),
    url(r'^assets/', include('assets.urls', namespace='assets'))
]

assets/models.py
from django.db import models
from users.models import UserGroup, UserProfile

# Create your models here.

class Asset(models.Model):
    STATUS_CHOICES = (
        ('In use', 'In use'),
        ('Out of use', 'Out of use'),
    )
    TYPE_CHOICES = (
        ('Server', 'Server'),
        ('VM', 'VM'),
        ('Storage', "Storage"),
        ('Openstack','Openstack'),
        ('Openstack2','Openstack二期'),
    )
    ENV_CHOICES = (
        ('Prod', 'Production'),
        ('Test', 'Testing'),
    )

    # Important
    ip = models.GenericIPAddressField(max_length=32, verbose_name='IP', db_index=True)
    other_ip = models.CharField(max_length=255, blank=True, null=True, verbose_name=u"其他IP")
    hostname = models.CharField(max_length=128, unique=True, verbose_name='Hostname')
    port = models.IntegerField(default=22, verbose_name='Port')
    groups = models.ManyToManyField(UserGroup, blank=True,
                                    verbose_name='Asset groups')
    admin_user = models.ForeignKey(UserProfile, null=True, blank=True,
                                   on_delete=models.SET_NULL, verbose_name="Admin user")
    system_users = models.CharField(blank=True,null=True,max_length=64,
                                          verbose_name="System User")
    idc = models.ForeignKey('IDC', blank=True, null=True,
                            on_delete=models.SET_NULL, verbose_name='IDC')
    is_active = models.BooleanField(default=True, verbose_name='Is active')
    type = models.CharField(choices=TYPE_CHOICES, max_length=16, blank=True, null=True,
                            default='Server', verbose_name='Asset type')
    env = models.CharField(choices=ENV_CHOICES, max_length=8, blank=True, null=True,
                           default='Prod', verbose_name='Asset environment')
    status = models.CharField(choices=STATUS_CHOICES, max_length=12, null=True, blank=True,
                              default='In use', verbose_name='Asset status')

    # Collect
    vendor = models.CharField(max_length=64, null=True, blank=True, verbose_name='Vendor')
    model = models.CharField(max_length=54, null=True, blank=True, verbose_name='Model')
    sn = models.CharField(max_length=128, null=True, blank=True, verbose_name='Serial number')

    cpu_model = models.CharField(max_length=64, null=True, blank=True, verbose_name='CPU model')
    cpu_count = models.IntegerField(null=True, verbose_name='CPU count')
    cpu_cores = models.IntegerField(null=True, verbose_name='CPU cores')
    memory = models.CharField(max_length=64, null=True, blank=True, verbose_name='Memory')
    disk_total = models.CharField(max_length=1024, null=True, blank=True, verbose_name='Disk total')
    disk_cloud = models.CharField(max_length=1024, null=True, blank=True, verbose_name='Disk cloud')

    os = models.CharField(max_length=128, null=True, blank=True, verbose_name='OS')
    os_version = models.CharField(max_length=16, null=True, blank=True, verbose_name='OS version')
    os_arch = models.CharField(max_length=16, blank=True, null=True, verbose_name='OS arch')

    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='Date created')
    comment = models.TextField(max_length=128, default='', blank=True, verbose_name='Comment')

    def __unicode__(self):
        return '%s <%s: %s>' % (self.hostname, self.ip, self.port)
    __str__ = __unicode__


class IDC(models.Model):
    name = models.CharField(max_length=32, verbose_name='Name')
    bandwidth = models.CharField(
        max_length=32, blank=True, verbose_name='Bandwidth')
    contact = models.CharField(
        max_length=128, blank=True, verbose_name='Contact')
    phone = models.CharField(max_length=32, blank=True,
                             verbose_name='Phone')
    address = models.CharField(
        max_length=128, blank=True, verbose_name="Address")
    intranet = models.TextField(blank=True, verbose_name='Intranet')
    extranet = models.TextField(blank=True, verbose_name='Extranet')
    date_created = models.DateTimeField(
        auto_now_add=True, null=True, verbose_name='Date created')
    operator = models.CharField(
        max_length=32, blank=True, verbose_name='Operator')
    created_by = models.CharField(
        max_length=32, blank=True, verbose_name='Created by')
    comment = models.TextField(blank=True, verbose_name='Comment')

    def __unicode__(self):
        return self.name
    __str__ = __unicode__

assets/forms.py
#!/usr/bin/env python
#_*_ coding:utf-8 _*_
from django import forms
from assets.models import Asset

class AssetForm(forms.ModelForm):

    class Meta:
        model = Asset

        fields = [
            "ip", "other_ip", "hostname", "port", "groups", "admin_user", "system_users", "idc",
            "is_active", "type", "env", "status", "vendor", "model", "sn", "cpu_model", "cpu_count",
            "cpu_cores", "memory", "disk_total", "disk_cloud", "os", "os_version", "os_arch", "comment"
        ]

assets/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from assets import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from assets.forms import *
from c13.api import *

@login_required
def AssetListView(request):

    #搜索功能
    if request.method == 'POST':
        assets = models.Asset.objects.all()
        infos = request.POST.get('ipnmb','')
        if infos:
            assets = assets.filter(Q(ip__icontains=infos) | Q(admin_user__name__icontains=infos))
            return render(request, 'assets/host_list.html',
                          {'contacts': assets},
                          )

    assets = models.Asset.objects.all().order_by('-ip')
    paginator = Paginator(assets, 5)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)

    return render(request, 'assets/host_list.html',
                  {'contacts': contacts},
                  )
@login_required
def AssetDetailView(request):
    asset_id = request.GET.get('id', '')
    assets = models.Asset.objects.all()
    if asset_id:
        assets = assets.filter(Q(id__contains=asset_id))

        return render(request, 'assets/host_detail.html',
                      {'assets':assets}
                      )
@login_required
def AssetDeleteView(request):
    asset_id = request.GET.get('id', '')
    if asset_id:
        models.Asset.objects.filter(id=asset_id).delete()

    if request.method == 'POST':
        asset_batch = request.GET.get('arg', '')
        asset_id_all = str(request.POST.get('asset_id_all', ''))

        if asset_batch:
            for asset_id in asset_id_all.split(','):
                asset = get_object_or_404(models.Asset, id=asset_id)
                asset.delete()

    return HttpResponseRedirect('/assets/asset')


@login_required
def AssetCreateView(request):

    af = AssetForm()
    if request.method == 'POST':
        af_post = AssetForm(request.POST)
        ip = request.POST.get('ip', '')
        hostname = request.POST.get('hostname', '')
        try:
            if Asset.objects.filter(hostname=hostname):
                error = u'该主机名 %s 已存在！' % hostname
                raise ServerError(error)
            if len(hostname) > 64:
                error = u'主机名长度不能超过64位！'
                raise ServerError(error)
        except ServerError:
            pass

        else:
            if af_post.is_valid():
                asset_save = af_post.save(commit=False)
                if not ip:
                    asset_save.ip = hostname

                asset_save.save()
                af_post.save_m2m()

                msg = u'主机 %s 添加成功' % hostname
                return HttpResponseRedirect('/assets/asset')
            else:
                esg = u'主机 %s 添加失败' % hostname


    return render(request, 'assets/host_create.html', locals())

assets/templates/assets/host_create.html
{% extends 'index.html' %}
{% load static %}
{% load bootstrap3 %}

{% block page-content %}

    <div class="row">
    <div class="col-sm-8">
        <form action="" method="post" class="form-horizontal">
    {% if af.non_field_errors %}
        <div class="alert alert-danger">
        {{ af.non_field_errors }}
        </div>
    {% endif %}
    {% csrf_token %}
    <h3>基础配置</h3>
        {% bootstrap_field af.ip layout="horizontal" %}
        {% bootstrap_field af.other_ip layout="horizontal" %}
        {% bootstrap_field af.hostname layout="horizontal" %}
        {% bootstrap_field af.port layout="horizontal" %}
        {% bootstrap_field af.groups layout="horizontal" %}
        {% bootstrap_field af.admin_user layout="horizontal" %}
        {% bootstrap_field af.system_users layout="horizontal" %}
        {% bootstrap_field af.idc layout="horizontal" %}

        {% bootstrap_field af.is_active layout="horizontal" %}
        {% bootstrap_field af.type layout="horizontal" %}
        {% bootstrap_field af.env layout="horizontal" %}
        {% bootstrap_field af.status layout="horizontal" %}
        {% bootstrap_field af.vendor layout="horizontal" %}
        {% bootstrap_field af.model layout="horizontal" %}
        {% bootstrap_field af.sn layout="horizontal" %}
        {% bootstrap_field af.cpu_model layout="horizontal" %}
        {% bootstrap_field af.cpu_cores layout="horizontal" %}
        {% bootstrap_field af.cpu_count layout="horizontal" %}
        {% bootstrap_field af.memory layout="horizontal" %}
        {% bootstrap_field af.disk_total layout="horizontal" %}
        {% bootstrap_field af.disk_cloud layout="horizontal" %}
        {% bootstrap_field af.os_arch layout="horizontal" %}
        {% bootstrap_field af.os layout="horizontal" %}
        {% bootstrap_field af.os_version layout="horizontal" %}
        {% bootstrap_field af.comment layout="horizontal" %}

    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <button class="btn btn-default" type="reset" > 重制</button>
            <button id="submit_button" class="btn btn-primary" type="submit">提交</button>
        </div>
    </div>
    </form>
</div>
    </div>
{% endblock %}

{% block custom_foot_js %}
<script>
function format(item) {
   var group = item.element.parentElement.label;
   return group + ':' + item.text;
}

$(document).ready(function () {
    $('.select2').select2({
        allowClear: true
    });
    $(".labels").select2({
        allowClear: true,
        templateSelection: format
    });
})
</script>
{% endblock %}

assets/templates/assets/host_detail.html
{% extends 'index.html' %}
{% load custom_tags %}
{% block page-title %}
{% load static %}

主机详情
{% endblock %}
{% block page-content %}

<div class="row">
     <div class="col-sm-6 col-lg-3">
        <div class="panel" style="height: auto">
            <div class="panel-heading">
                <h3 class="panel-title">主机信息</h3>
            </div>
            <div  class="panel-body " style="overflow: auto" >
                {%for asset in assets%}
                <div class="ibox-content">
                    <table class="table">
                        <tbody>
                        <tr class="no-borders-tr">
                            <td>主机名：</td>
                            <td><b>{{ asset.hostname|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>IP：</td>
                            <td><b>{{ asset.ip|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td class="text-navy">其他IP:</td>
                            <td>
                                <table class="table">
                                    {% if asset.other_ip %}
                                        {% for ip in asset.other_ip|ip_str_to_list %}
                                            <tr>
                                                <td>{{ ip|default_if_none:"" }}</td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>port：</td>
                            <td><b>{{ asset.port|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>groups：</td>
                            <td><b>{{ asset.get_groups|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>admin_user：</td>
                            <td><b>{{ asset.admin_user|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>system_users：</td>
                            <td><b>{{ asset.system_users|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>idc：</td>
                            <td><b>{{ asset.idc|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>type：</td>
                            <td><b>{{ asset.type|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>env：</td>
                            <td><b>{{ asset.env|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>status：</td>
                            <td><b>{{ asset.status|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>vendor：</td>
                            <td><b>{{ asset.vendor|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>model：</td>
                            <td><b>{{ asset.model|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>sn：</td>
                            <td><b>{{ asset.sn|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>cpu_model：</td>
                            <td><b>{{ asset.cpu_model|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>cpu_count：</td>
                            <td><b>{{ asset.cpu_count|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>cpu_cores：</td>
                            <td><b>{{ asset.cpu_cores }}</b></td>
                        </tr>
                        <tr>
                            <td>memory：</td>
                            <td><b>{{ asset.memory|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>disk_total：</td>
                            <td><b>{{ asset.disk_total|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>disk_cloud：</td>
                            <td><b>{{ asset.disk_cloud|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>os：</td>
                            <td><b>{{ asset.os|default_if_none:"" }} {{ asset.os_version|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>os_arch：</td>
                            <td><b>{{ asset.os_arch|default_if_none:"" }}</b></td>
                        </tr>
                        <tr>
                            <td>date_created：</td>
                            <td><b>{{ asset.date_created|date:"Y-m-d" }}</b></td>
                        </tr>
                        <tr>
                            <td>comment：</td>
                            <td><b>{{ asset.comment|default_if_none:"" }}</b></td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                {%endfor%}
            </div>
        </div>
     </div>

    <div class="col-sm-6 col-lg-9">
        <div class="panel">
             <div class="panel-heading">
                <h3 class="panel-title">主机监控</h3>
            </div>
        </div>
        <div class="panel" style="width: auto">
            <div class="col-md-4">
                <div id="cpu" style="width: 300px;height: 300px;"></div>
            </div>
        </div>
        <div class="panel" style="width: auto">
            <div class="col-md-4">
                <div id="mem" style="width: 300px;height: 300px;"></div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-9">
        <div class="panel" style="left: auto">
            <div class="col-md-4">
                <div id="disk" style="width: 300px;height: 300px;"></div>
            </div>
        </div>
        <div class="panel" style="right: auto">
            <div class="col-md-8">
                <div id="network" style="width: 500px;height: 300px;"></div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/plugins/echarts.min.js' %}"></script>
<script type="text/javascript">

var cpu = echarts.init(document.getElementById('cpu'));
    option = {
        tooltip : {
            formatter: "{a} <br/>{b} : {c}%"
        },
        series: [
            {
                name: 'CPU',
                type: 'gauge',
                detail: {formatter:'{value}%'},
                data: [{value: 45, name: 'CPU'}]
            }
        ]
    };
    cpu.setOption(option);

var mem = echarts.init(document.getElementById('mem'));
    option = {
        tooltip : {
            formatter: "{a} <br/>{b} : {c}%"
        },
        series: [
            {
                name: 'mem',
                type: 'gauge',
                detail: {formatter:'{value}%'},
                data: [{value: 45, name: 'mem'}]
            }
        ]
    };
    mem.setOption(option);


var disk = echarts.init(document.getElementById('disk'));

    option = {
        tooltip : {
            formatter: "{a} <br/>{b} : {c}%"
        },
        series: [
            {
                name: 'mem',
                type: 'gauge',
                detail: {formatter:'{value}%'},
                data: [{value: 200, name: 'disk'}]
            }
        ]
    };
    disk.setOption(option);

var network = echarts.init(document.getElementById('network'));
    option = {
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            }
        },
        toolbox: {
            show: true,
            feature: {
                saveAsImage: {}
            }
        },
        xAxis:  {
            type: 'category',
            boundaryGap: false,
            data: ['00:00', '01:15', '02:30', '03:45', '05:00', '06:15', '07:30', '08:45', '10:00', '11:15', '12:30', '13:45', '15:00', '16:15', '17:30', '18:45', '20:00', '21:15', '22:30', '23:45']
        },
        yAxis: {
            type: 'value',
            axisLabel: {
                formatter: '{value} K'
            },
            axisPointer: {
                snap: true
            }
        },
        series: [
            {
                type:'line',
                smooth: true,
                data: [300, 280, 250, 260, 270, 300, 550, 500, 400, 390, 380, 390, 400, 500, 600, 750, 800, 700, 600, 400]
            }
        ]
    };

    network.setOption(option);
</script>
{% endblock %}

assets/templates/assets/host_list.html
{% extends 'index.html' %}
{% load custom_tags %}
{% block page-title %}
操作主机
{% endblock %}

{% block page-content %}
    <div class="row" >
        <div class="col-lg-3" >
             <div class="panel" >
                <div class="pannel-heading">
                    <h3 class="panel-title">主机组</h3>
                </div>
                <div class="pannel-body">
                    <div class="list-group bord-no">

                        {% ifequal selected_g_id '-1' %}
                            <a class="list-group-item active" href="/hosts/?selected_group=-1"><b>最近登录 [{{ recent_logins|length }}]</b></a>
                        {% else %}
                             <a class="list-group-item" href="/hosts/?selected_group=-1">最近登录 [{{ recent_logins|length }}]</a>
                        {% endifequal %}
                        {% ifequal selected_g_id '-2' %}
                            <a class="list-group-item active" href="/hosts/?selected_group=-2"><b>未分组主机 [{{ request.user.bind_hosts.select_related.count }}]</b></a>
                        {% else %}
                             <a class="list-group-item" href="/hosts/?selected_group=-2">未分组主机 [{{ request.user.bind_hosts.select_related.count }}]</a>
                        {% endifequal %}

                        {% for g in request.user.host_groups.select_related %}
                            {% ifequal g.id selected_g_id %}
                                <a class="list-group-item active" href="{% url 'host_list'  %}?selected_group={{g.id}}"><b>{{g.name }} [{{ g.bind_hosts.select_related.count }}]</b></a>
                            {% else %}
                                <a class="list-group-item" href="{% url 'host_list'  %}?selected_group={{g.id}}"><b>{{g.name }} [{{  g.bind_hosts.select_related.count}}]</b></a>
                            {% endifequal %}

                        {% endfor %}
                    </div>
                </div>
             </div>
        </div>

        <div class="col-lg-9" >
             <div class="panel" >
             <div class="panel-heading">
                 <div class="pannel-heading" style="float: left">
                     <h3 class="panel-title">主机列表</h3>
                 </div>
                 <div style="float: right;">
                    <form role="form" method="post">{% csrf_token %}
                        <div class="searchbox panel-heading">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search.." name="ipnmb">
                            <span class="input-group-btn">
                                <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                    </form>
                 </div>
             </div>
                 <div class="pannel-body" id="asset_form">
                     <div class="list-group" >
                         <div class="table-responsive">
                            <table class="table table-condensed">
                                <thead>
                                    <tr>
                                        <th class="text-center">
                                        <input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('asset_form')">
                                        </th>
                                        <th class="text-center">IP地址</th>
                                        <th class="text-center">主机名</th>
                                        <th class="text-center">机房</th>
                                        <th class="text-center">管理用户</th>
                                        <th class="text-center">系统</th>
                                        <th class="text-center">配置</th>
                                        <th class="text-center">操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for g in contacts %}
                                        <tr>
                                            <td class="text-center" name="id" value="{{ g.id }}" data-editable='false'>
                                                <input name="id" value="{{ g.id }}" type="checkbox" class="i-checks">
                                            </td>
                                            <td class="text-center"><a href="{% url 'assets:asset_detail'%}?id={{ g.id}}">{{ g.ip }}</a></td>
                                            <td class="text-center"><a href="{% url 'assets:asset_detail'%}?id={{ g.id}}" class="">{{ g.hostname }}</a></td>
                                            <td class="text-center"><a href="#" class="">{{ g.idc.name }}</a></td>
                                            <td class="text-center"><a class="">{{ g.admin_user }}</a></td>
                                            <td class="text-center"><span class="">{{ g.os }}{{ g.os_version }}</span></td>
                                            <td class="text-center"><span class="">{{ g.cpu_count }}C/{{ g.memory }}G/{{ g.disk_total }}G/{{ g.disk_cloud }}/G</span></td>
                                            <td class="text-center">
                                                <span class="btn btn-success" style="height: 25px;width: 50px"><a href="#">连接</a></span>
                                                <span class="btn btn-danger" style="height: 25px;width: 50px"><a href="{% url 'assets:asset_delete' %}?id={{ g.id }}">删除</a></span>
                                                <span class="btn btn btn-warning" style="height: 25px;width: 50px">更改</span>
                                            </td>
                                        </tr>
                                   {% endfor %}
                                </tbody>
                            </table>
                         </div> <!--end table div-->
                     </div>
                     <div class="col-sm-6">
                        <div class="col-sm-6">
                            <input type="button" id="asset_del" class="btn btn-danger btn-sm" value="批量删除" />
                            <a href="{% url 'assets:asset_create'%}" type="button" class="btn btn-info">添加主机</a>
                        </div>
                     </div>

                 </div>
             </div>

            <!--分页功能 -->
            <div class="panel-heading" style="float: right;">
                <nav>
                    <ul class="pagination">
                        {% if contacts.has_previous %}
                            <li class=""><a href="?page={{ contacts.previous_page_number }}" aria-label="Previous">&laquo;</a></li>
                        {% endif %}
                            {% for page_num in contacts.paginator.page_range %}
                                {% guess_page contacts.number page_num %}
                            {% endfor %}
                        {% if server_cmdb_obj.has_next %}
                            <li class=""><a href="?page={{ contacts.next_page_number }}" aria-label="Next">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
<script type="text/javascript" >


</script>

{% endblock %}