c13/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from c13 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexViews),
    url(r'^personal/', views.personal, name='personal'),
    url(r'^accounts/logout/',views.logout,name='logout'),
    url(r'^accounts/login/',views.login,name='login'),
    url(r'^assets/', include('assets.urls', namespace='assets'))
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class UserProfile(models.Model):
    ROLE_ADMIN = 'Admin'
    ROLE_USER = 'User'

    ROLE_CHOICES = (
        (ROLE_ADMIN, 'Administrator'),
        (ROLE_USER, 'User'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    email = models.EmailField(max_length=128, unique=True, verbose_name='Email')
    groups = models.ForeignKey('UserGroup', related_name='users', blank=True, verbose_name='User group',on_delete=models.CASCADE)
    role = models.CharField(choices=ROLE_CHOICES, default='User', max_length=10, blank=True, verbose_name='Role')
    avatar = models.ImageField(upload_to="avatar", blank=True, null=True, verbose_name='Avatar')
    wechat = models.CharField(max_length=128, blank=True, verbose_name='Wechat')
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name='Phone')
    date_created = models.DateTimeField(auto_now_add=True, null=True,
                                        verbose_name='Date created')
    valid_begin_time = models.DateTimeField(default=timezone.now, help_text="yyyy-mm-dd HH:MM:SS")
    valid_end_time = models.DateTimeField(blank=True, null=True, help_text="yyyy-mm-dd HH:MM:SS")
    created_by = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.name



class UserGroup(models.Model):
    name = models.CharField(max_length=128, verbose_name='Name')
    comment = models.TextField(blank=True, verbose_name='Comment')
    date_created = models.DateTimeField(auto_now_add=True, null=True,
                                        verbose_name='Date created')
    created_by = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

templates/_foot_js.html
{% load static %}


	<!--jQuery [ REQUIRED ]-->
	<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>

	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="{% static 'js/bootstrap.min.js'%}"></script>

	<!--Fast Click [ OPTIONAL ]-->
	<script src="{% static 'js/fastclick.min.js'%}"></script>

	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="{% static 'js/nifty.min.js' %}"></script>
	<script src="{% static 'plugins/bootstrap-select/bootstrap-select.min.js'%}"></script>
	<script src="{% static 'plugins/js.cookie.js' %}"></script>
	<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
	<script src="{% static 'plugins/bootstrap-fileinput/js/fileinput.js' %}"></script>
	<script src="{% static 'plugins/bootstrap-fileinput/js/plugins/canvas-to-blob.js' %}"></script>
	<script src="{% static 'plugins/bootstrap-fileinput/js/fileinput_locale_zh.js' %}"></script>

    <script src="{% static 'plugins/bootstrap-validator/bootstrapValidator.js'%}"></script>
    <script src="{% static 'plugins/highstock/js/highstock.js' %}"></script>
    <script src="{% static 'plugins/highstock/js/modules/exporting.js' %}"></script>

	<!--Bootstrap Timepicker [ OPTIONAL ]-->
	<script src="{% static 'plugins/bootstrap-timepicker/bootstrap-timepicker.min.js' %}"></script>
	<!--Bootstrap Datepicker [ OPTIONAL ]-->
	<script src="{% static 'plugins/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>


    <script src="{% static 'plugins/dropzone/dropzone_latest.js' %}"></script>

    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>

templates/_nav.html
{% load static %}
<div class="navbar-content clearfix">
    <ul class="nav navbar-top-links pull-left">

        <li class="tgl-menu-btn">
            <a class="mainnav-toggle" href="#">
                <i class="fa fa-navicon fa-lg"></i>
            </a>
        </li>
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <!--End Navigation toogle button-->

    </ul>
    <ul class="nav navbar-top-links pull-right">

        <!--User dropdown-->
        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
        <li id="dropdown-user" class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle text-right">
                <span class="pull-right">
                    <img class="img-circle img-user media-object" src="{% static 'img/av1.png' %}" alt="Profile Picture">
                </span>
                <div class="username hidden-xs">{{ request.user.userprofile.name }}</div>
            </a>

            <div class="dropdown-menu dropdown-menu-md dropdown-menu-right with-arrow panel-default">
                <!-- User dropdown menu -->
                <ul class="head-list">
                    <li>
                        <a href="{% url 'personal' %}">
                            <i class="fa fa-user fa-fw fa-lg"></i> 个人信息
                        </a>
                    </li>

                </ul>

                <!-- Dropdown footer -->
                <div class="pad-all text-right">
                    <a href="{% url 'logout' %}" class="btn btn-primary">
                        <i class="fa fa-sign-out fa-fw"></i> Logout
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>

templates/audit.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
用户审计
{% endblock %}

{% block page-content %}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            ff
        </h3>
    </div>
    <div class="panel-body">
        {% if  table_obj.list_filter%}
        <form >
            <div class="row">
                {% for filter_column in table_obj.list_filter %}
                    <div class="col-md-3" style="margin-bottom: 15px">
                        {{ filter_column.verbose_name }}
                        <select name="{{ filter_column.column_name }}" class="form-control" >
                            {% for choice in filter_column.choices %}
                                {% if filter_column.selected == choice.0|to_string  %}
                                    <option value="{{ choice.0 }}" selected>{{ choice.1 }}</option>
                                {% else %}
                                    <option value="{{ choice.0 }}" >{{ choice.1 }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                {% endfor %}
                <div class="col-md-3">
                    <input type="submit" class="btn btn-success" value="开始过滤">
                </div>
            </div>
        </form>
        {% endif %}

        <table id="audit_log_list" class="table table-hover">
            <thead>
                <tr class="">

                    {% for column in table_obj.list_display %}
                        <th class="column-sorted">
                            <a href="?page={{ table_obj.query_sets.number }}&orderby={% if table_obj.orderby_col_index == forloop.counter0 %}{{ table_obj.orderby_field}}{% else %}{{ column }}{% endif %}" >
                                {% get_table_column column table_obj %}
                                {% display_orderby_arrow table_obj forloop.counter0 %}

                            </a>
                        </th>

                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in table_obj.query_sets %}
                    <tr>
{#                        {% build_table_row  row table_obj 'id'  'audit'  %}#}
                        {% build_table_row  row table_obj    %}
                    </tr>
                {% endfor %}

            </tbody>
            <footer>
              <tr>
                    <td colspan="12" class="footable-visible">
                        <div class="pagination">

                            <nav>
                                <p>共{{ paginator.count }}条数据</p>
                                <ul class="pagination">
                                    {% if table_obj.query_sets.has_previous %}
                                    <li class="disabled">
                                        <a href="{{ request.get_full_path }}?page={{ table_obj.query_sets.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                                    </li>
                                    {% endif %}
                                    {% for p_num in paginator.page_range %}
                                        {% render_page_num request table_obj.query_sets p_num %}
                                    {% endfor %}
                                    {% if customer_list.has_next %}
                                    <li>
                                      <a href="{{ request.get_full_path }}?page={{ table_obj.query_sets.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                      </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>

                        </div>    <!--end pagination-->

                    </td>
              </tr>
            </footer>

        </table>
    </div>
</div>

{% endblock%}

templates/crontab.html
{% extends 'index.html' %}

{% block page-content %}

    <div class="panel">

        <div class="panel-body">
            <h2>开发者:小主莫急,此页正在施工中！</h2>
            <h2>用户:那放上来干屁？</h2>
            <h2>开发者:我愿意我愿意我愿意,用你管！</h2>
            <h2>用户:。。。。擦，有本事告诉我你是谁，我保证不打死你！</h2>
            <h2>开发者:加群Python自动化交流群255012808</h2>
            <h2>开发者:加群Python开发之路 304154367</h2>
        </div>

    </div>

{% endblock %}

templates/host_detail.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
主机详情
{% endblock %}
{% block page-content %}

<div class="row">
     <div class="col-sm-6 col-lg-3">
        <div class="panel" style="height: 492px;">
            <div class="panel-heading">
                <h3 class="panel-title">主机列表</h3>
            </div>
            <div  class="panel-body " style="overflow: auto" >

                      <input style="margin-bottom: 5px" type="text" oninput="SearchHost(this)" id="host_search" class="form-control" placeholder="查找主机...">

                <div id="host_list" style="">
                    <div style="margin-bottom:0;" class="list-group bg-trans">
                     {% for host in all_hosts %}

                            {% if host.id == current_host_id %}
                                <a class="list-group-item active" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}">{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% else %}
                                <a class="list-group-item" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}" >{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% endif %}
                     {% endfor %}
                     </div>
                </div>




            </div>
        </div>
     </div>

    <div class="col-sm-6 col-lg-9">
        <div class="panel">
             <div class="panel-heading">
                <h3 class="panel-title">主机信息</h3>
            </div>
            <div class="panel-body" >

                {% for host in all_hosts %}

                    {% if host.id == current_host_id %}
                    <div class="row" >
                        <label class="col-md-2 control-label">主机名(IP)</label>
                        <div  class="col-md-9 ">
                            <b>{{ host }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">操作系统</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.system_type }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">端口</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.port }}</b>
                        </div>
                    </div>

                    <div class="row" >
                        <label class="col-md-2 control-label">所在机房</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.idc }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">主机状态</label>
                        <div  class="col-md-9 ">
                            {% if host.enabled %}
                            <span class="badge badge-success">已启用</span>
                            {% else %}
                            <span class="badge badge-danger">已停用</span>
                            {% endif %}
                        </div>
                    </div>


                    <div class="row" >
                        <label class="col-md-2 control-label">已绑定远程用户信息</label>
                        <div  class="col-md-9 ">
                            {% for bind_host in host.bindhosts_set.select_related %}
                            <div><b>{{ bind_host.host_user.username }}
                                -->属组:{% for group in  bind_host.hostgroups_set.select_related %}
                                    <span class="badge badge-info">{{ group.name }}</span>{% endfor %}</b>
                                {% if not bind_host.enabled %}<span class="badge badge-danger">此账户已禁用</span>{% endif %}
                            </div>

                            {% endfor %}
                        </div>
                    </div>


                    <div class="row" >
                        <hr/>
                        <label class="col-md-2 control-label panel-title">用户访问纪录</label>

                        <table class="table table-hover">
                            <tr>
                                <th>会话ID</th>
                                <th>操作用户</th>
                                <th>远程用户</th>
                                <th>登录日期</th>
                                <th>停留时长</th>
                                <th>命令数</th>
                                <th>状态</th>

                            </tr>
                            {% for log in access_records %}
                            <tr>
                                <td>{{ log.id }}</td>
                                <td data-label="hostname" class="hide" >{{ log.host.host.hostname }}</td>
                                <td>{{ log.user.name }}</td>
                                <td data-label="username">{{ log.bind_host.host_user.username }}</td>
                                <td data-label="login-date">{{ log.date |date:"Y-m-d H:i:s" }}</td>
                                <td data-label="stay-time">{% get_time_humanize_display log.stay_time %}</td>
{#                                <td data-label="logout-date">{% query_logout_date  log.session.auditlog_set.select_related 'action_type' 2 %}</td>#}
                                <td ><a href="#" onclick="ShowRecordDetail(this,'{{ log.session.id }}')" class="btn-link">{{ log.cmd_count }}</a></td>
                                {% if log.closed %}
                                    <td ><span class="badge badge-info">已结束</span></td>
                                {% else %}
                                    <td><span class="badge badge-success">连接中</span></td>
                                {% endif %}
                            </tr>
                            {% endfor %}

                        </table>
                        <div class="pagination pull-right ">
                            {% pagenator2 access_records 'host_id' current_host_id %}
                        </div>
                    </div>




                    {% endif %}

                {% endfor %}

            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block bottom-js %}
<script type="text/javascript">

    $(document).ready(function(){

        host_list = {};
        $("#host_list div").children().each(function(index){

          host_list[$(this).attr("host_id")] = $(this).text();
        });

        $("#host_list a[host_id='" + "{{ current_host_id }}" + "']").prependTo("#host_list div");
        console.log($("#host_list active")[0])


    });//end doc ready

    function SearchHost(ele){

        var search_str = $(ele).val()
        var host_list_html ='' ;

        $.each(host_list,function(host_id,val){
            if (val.indexOf(search_str) >-1){
                console.log(val);
                var html_row = "<a class='list-group-item' host_id='" + host_id + "' href='/host/detail/?host_id=" + host_id + "' > " + val + "</a>";
                host_list_html += html_row ;

            }

        });//end each

        $("#host_list").html(host_list_html);
    }


</script>
{% endblock %}

templates/multi_task_action_component.html
        <div class="col-sm-7 col-lg-9 pull-right task_res_div">
            <div class="panel ">

                <!-- Panel heading -->
                <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                <div class="pannel-heading">
                    <div class="panel-control">
                        <button class="btn btn-default " type="button" data-toggle="collapse" data-target="#demo-chat-body" aria-expanded="true">
                            <i class="fa fa-chevron-down "></i>
                        </button>
                    </div>
                    <h3 class="panel-title">{% block multi_task_action_title %}批量文件分发{% endblock %}</h3>
                </div>

                <!-- Panel body -->
                <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
                <div class="panel-body">
                    <!-- Content here -->

                    <div class="pad-ver">


                            <!--Send button-->
                          <select name="task_expire_time" class="btn-info">
                            <option value="30">任务超时时间(30分钟)</option>
                            <option value="45">45分钟</option>
                            <option value="60">60分钟</option>
                            <option value="90">90分钟</option>
                            <option value="120">120分钟</option>
                            <option value="180">180分钟</option>
                          </select>


                            <!--Send button-->
                            <button id="task-exec-btn" type="button" class="btn btn-success btn-labeled">
                                <span class="btn-label"><i class="fa fa-bicycle"></i></span> 执行命令
                            </button>

                            <!--Save draft button-->
                            <button id="mail-save-btn" type="button" class="btn btn-danger btn-labeled">
                                <span class="btn-label"><i class="fa fa-stop"></i></span> 停止
                            </button>

                    </div>
                    <br>
                    {% include 'multi_task_result_display_component.html' %}

                </div>
            </div> <!--end panel-default-->
        </div> <!--end col-lg-9-->

templates/user_audit.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
用户审计
{% endblock %}
{% block page-content %}
<div class="row" >
    <div class="col-sm-6 col-lg-3">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">用户列表</h3>
            </div>
            <div class="panel-body" >
                <div class="list-group bord-no">

                {% for department in department_list %}
                    <a data-label="department-name" class=" list-group-item" href="#"><b>{{ department }}</b><span style="color:red" class="badge badge-info">{{ department.userprofile_set.select_related|length }}</span></a>
                    {% for user in department.userprofile_set.select_related %}

                        <a data-label="username"  user-id="{{ user.id }}" style="margin-left:2%;width:96%" class="list-group-item  collapse" href="/user_audit/{{ user.id }}/">&nbsp;&nbsp;&nbsp;{{ user.name }}</a>
                    {% endfor %}
                {% endfor %}
                </div>
            </div>
        </div>

    </div> <!--end col-lg-3-->
    <div class="col-sm-6 col-lg-9">
        <div class="panel">

            <div class="panel-body" style="margin-left:0" >

                <div class="row" >
                    <label class="col-md-2 control-label">账户</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">部门</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.department.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">账户有效期</label>
                    <div  class="col-md-9 ">
                        从 <b>{{ user_obj.valid_begin_time }}</b> 至 <b>{{ user_obj.valid_end_time }}</b>
                        <hr/>
                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">可管理主机组</label>
                    <div  class="col-md-9 ">
                        {% for group in user_obj.host_groups.select_related %}
                        {{ group.name }}<br>
                        {% endfor %}
                    <hr/>
                    </div>
                </div>

                <div class="row" >
                    <label class="col-md-2 control-label">可操作主机列表</label>
                    <div  class="col-md-9 ">

                        <table class="table  table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>主机名</th>
                                <th>IP</th>
                                <th>远程用户</th>
                            </tr>
                        </thead>
                        <tbody>
                         {% for bind_host in user_obj.bind_hosts.select_related %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#fakelink" class="btn-link">{{ bind_host.host.hostname}}</a></td>
                                <td>{{  bind_host.host.hostname }} </td>
                                <td>{{  bind_host.host_user.username }} </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                        </table>


                     <hr/>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-lg-12">

        <div class="panel panel-primary">

            <!--Panel heading-->
            <div class="panel-heading">
                <div class="panel-control">

                    <!--Nav tabs-->
                    <ul class="nav nav-tabs">
                        {% if data_type == 'multi_task' %}

                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% else %}
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% endif %}
                    </ul>

                </div>
                <h3 class="panel-title"><b>{{ user_obj.name }}</b> 的操作纪录</h3>
            </div>

            <!--Panel body-->
            <div class="panel-body">

                <!--Tabs content-->
                <div class="tab-content">
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-1" class="tab-pane fade">
                    {% else %}
                    <div id="demo-tabs-box-1" class="tab-pane fade active in ">
                    {% endif %}
                      <table class="table  table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>#</th>

                                    <th>主机名</th>
                                    <th>IP</th>
                                    <th>远程用户</th>
                                    <th>登录日期</th>
                                    <th>登出日期</th>
                                    <th>操作指令数</th>
                                    <th>#</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for record in user_login_records %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td data-label="hostname"><a href="#fakelink" class="btn-link">{{ record.host.host.hostname}}</a></td>
                                    <td data-label="ip_addr">{{ record.host.host.ip_addr }} </td>
                                    <td data-label="username">{{ record.host.host_user.username }} </td>
                                    <td data-label="login_date"><b >{{ record.date|date:"Y-m-d H:i" }}</b> </td>
                                    <td data-label="logout_date">{{ record.session.auditlog_set.select_related.last.date|date:"Y-m-d H:i" }} </td>
                                    <td>{{ record.session.auditlog_set.select_related.count}} </td>
                                    <td><a onclick="ShowRecordDetail(this,'{{ record.session.id }}')"  class="badge badge-success">查看详细</a> </td>
                                </tr>
                                {% endfor %}
                           </tbody>

                      </table>

                    <div class="pagination pull-right ">
                        {% pagenator user_login_records 'cmd_log' %}
                    </div>

                    </div>
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-2" class="tab-pane fade active in">
                    {% else %}
                    <div id="demo-tabs-box-2" class="tab-pane fade">
                    {% endif %}

                          <table class="table  table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>

                                        <th>任务ID</th>
                                        <th>任务类型</th>
                                        <th>任务内容</th>
                                        <th>成功数</th>
                                        <th>失败数</th>
                                        <th>未知数</th>
                                        <th>详细</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in multitask_records %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ record.id }}</td>
                                        <td>{{ record.task_type }}</td>
                                        <td>{{ record.cmd }}</td>
                                         <td>{% query_set record.tasklogdetail_set "result" "success" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "failed" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "unknown" %}</td>
                                        <td><a class="badge badge-info" href="{% url 'multi_task_log_detail' record.id %}">查看详细</a></td>

                                    </tr>
                                    {% endfor %}
                               </tbody>

                          </table>

                        <div class="pagination pull-right ">
                            {% pagenator multitask_records 'multi_task' %}
                        </div>


                    </div>
                </div>
            </div>
        </div>



    </div> <!--end col-sm-6 col-lg-12-->
</div>

{% include 'user_audit_modal.html' %}


{% endblock %}
{% block aside-bar %}

{% endblock %}
{% block bottom-js %}
{% include 'user_audit_js.html' %}
<script type="text/javascript" >


    $(document).ready(function(){

        if ("{{ data_type }}" == 'multi_task'){

        }

        $("a[data-label='department-name']").click(function(){
            $(this).toggleClass('active');

            $(this).nextUntil("a[data-label='department-name']").toggleClass("collapse");
        });//end click
        $("a[data-label='username']").click(function(){

            $(this).parent().children("a[data-label='username']").removeClass("btn-default");
            $(this).addClass("btn-default");

        });//end click


        //highlight the active user when page loaded
        var active_user_ele = $("a[user-id='{{ user_obj.id }}']");
        active_user_ele.toggleClass("collapse");
        if (active_user_ele.prev().attr('data-label') == 'department-name'){
            active_user_ele.prev().toggleClass('active');
        }else{
            var parent_node = active_user_ele.prevUntil("a[data-label='department-name']")[0];
            $(parent_node).prev().toggleClass('active');

        }
        //end highlight the active user when page loaded

    });


</script>
{% endblock %}